#!/usr/bin/env sh

signal() {
	xsetroot -name "fsignal:$*"
}

get_layout_index() {
  case "$1" in
    vtile)         echo 0 ;;
    floating)      echo 1 ;;
    monocle)       echo 2 ;;
    grid)          echo 3 ;;
    centered)      echo 4 ;;
    deck)          echo 5 ;;
    htile)         echo 6 ;;
    *)             echo 0 ;; # default to vtile
  esac
}

case $# in
1)
	case $1 in
	setlayout | view | viewall | togglebar | togglefloating | zoom | killclient | quit)
		signal $1
		;;
	*)
		echo "Unknown command or missing one argument."
		exit 1
		;;
	esac
	;;
2)
	case $1 in
  layout)
    signal setlayoutex i $(get_layout_index $2)
    ;;
	view)
		signal $1 ui $2
		;;
	viewex | toggleviewex | tagex | toggletagex | setlayoutex | focusstack | incnmaster | focusmon | tagmon)
		signal $1 i $2
		;;
	setmfact)
		signal $1 f $2
		;;
	*)
		echo "Unknown command or one too many arguments."
		exit 1
		;;
	esac
	;;
*)
	echo "Too many arguments."
	exit 1
	;;
esac
